In [1]:
import pandas as pd

In [2]:
files = ['202005.csv', '202006.csv', '202007.csv']

list = []

for file in files:
    x = pd.read_csv(file)
    list.append(x)

df = pd.concat(list)

df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,336,2020-05-01 00:01:06.3380,2020-05-01 00:06:42.9560,2017,E 43 St & 2 Ave,40.750224,-73.971214,465,Broadway & W 41 St,40.755136,-73.986580,18015,Subscriber,1993,1
1,853,2020-05-01 00:01:08.1950,2020-05-01 00:15:21.2150,3376,E 65 St & 2 Ave,40.764719,-73.962221,478,11 Ave & W 41 St,40.760301,-73.998842,35905,Subscriber,1989,1
2,78,2020-05-01 00:01:08.5260,2020-05-01 00:02:27.0490,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,3789,Fulton St & Irving Pl,40.681860,-73.959432,33350,Subscriber,1938,2
3,1185,2020-05-01 00:02:22.4380,2020-05-01 00:22:08.1220,3630,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,3506,Lexington Ave & E 120 St,40.801307,-73.939817,43790,Subscriber,1996,1
4,272,2020-05-01 00:02:32.8280,2020-05-01 00:07:05.0880,3776,Central Ave & Starr Street,40.700003,-73.928340,3068,Humboldt St & Varet St,40.703172,-73.940636,39912,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105803,877,2020-07-31 23:59:48.9250,2020-08-01 00:14:26.2540,217,Old Fulton St,40.702772,-73.993836,398,Atlantic Ave & Furman St,40.691652,-73.999979,44073,Customer,1969,0
2105804,839,2020-07-31 23:59:51.7740,2020-08-01 00:13:50.9750,4044,8 Ave & W 38 St,40.754610,-73.991770,3163,Central Park West & W 68 St,40.773407,-73.977825,41797,Customer,2002,1
2105805,1042,2020-07-31 23:59:56.1460,2020-08-01 00:17:18.5090,3723,Cadman Plaza E & Johnson St,40.695317,-73.990157,350,Clinton St & Grand St,40.715595,-73.987030,24808,Subscriber,1974,1
2105806,699,2020-07-31 23:59:57.4310,2020-08-01 00:11:36.5420,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,504,1 Ave & E 16 St,40.732219,-73.981656,41486,Subscriber,1991,1
2105807,249,2020-07-31 23:59:58.7260,2020-08-01 00:04:08.2070,446,W 24 St & 7 Ave,40.744876,-73.995299,3259,9 Ave & W 28 St,40.749370,-73.999234,28699,Customer,1990,1

In [4]:
df['gender'] = df['gender'].map({0: "Unknown", 1: "Male", 2: "Female"})

In [5]:
df.to_csv('2020_data.csv', index=False)

In [6]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,336,2020-05-01 00:01:06.3380,2020-05-01 00:06:42.9560,2017,E 43 St & 2 Ave,40.750224,-73.971214,465,Broadway & W 41 St,40.755136,-73.986580,18015,Subscriber,1993,Male
1,853,2020-05-01 00:01:08.1950,2020-05-01 00:15:21.2150,3376,E 65 St & 2 Ave,40.764719,-73.962221,478,11 Ave & W 41 St,40.760301,-73.998842,35905,Subscriber,1989,Male
2,78,2020-05-01 00:01:08.5260,2020-05-01 00:02:27.0490,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,3789,Fulton St & Irving Pl,40.681860,-73.959432,33350,Subscriber,1938,Female
3,1185,2020-05-01 00:02:22.4380,2020-05-01 00:22:08.1220,3630,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,3506,Lexington Ave & E 120 St,40.801307,-73.939817,43790,Subscriber,1996,Male
4,272,2020-05-01 00:02:32.8280,2020-05-01 00:07:05.0880,3776,Central Ave & Starr Street,40.700003,-73.928340,3068,Humboldt St & Varet St,40.703172,-73.940636,39912,Subscriber,1993,Male